export const GiftCards = [
  {
    id: 1,
    nome: "Gift Card Playstation 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 2,
    nome: "Gift Card Playstation 250R$",
    valor: 270,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 3,
    nome: "Gift Card Playstation 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 4,
    nome: "Gift Card Playstation 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 5,
    nome: "Gift Card Playstation 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 6,
    nome: "Gift Card Playstation Plus 3 Meses",
    valor: 90,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 7,
    nome: "Gift Card Playstation Plus 12 Meses",
    valor: 160,
    plataforma: "GiftCards",
    console: "Playstation",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 8,
    nome: "Gift Card Nintendo 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 9,
    nome: "Gift Card Nintendo 250R$",
    valor: 270,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 10,
    nome: "Gift Card Nintendo 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 11,
    nome: "Gift Card Nintendo 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 12,
    nome: "Gift Card Nintendo 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 13,
    nome: "Gift Card Nintendo online 3 Meses",
    valor: 90,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 14,
    nome: "Gift Card Nintendo Online 12 Meses",
    valor: 120,
    plataforma: "GiftCards",
    console: "Nintendo Switch",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 15,
    nome: "Gift Card Xbox 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 16,
    nome: "Gift Card Xbox 250R$",
    valor: 270,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 17,
    nome: "Gift Card Xbox 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 18,
    nome: "Gift Card Xbox 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 19,
    nome: "Gift Card Xbox 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 20,
    nome: "Gift Card Xbox GamePass 3 Meses",
    valor: 90,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 21,
    nome: "Gift Card Xbox GamePass Ultimate 12 Meses",
    valor: 155,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 22,
    nome: "Gift Card Steam 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 23,
    nome: "Gift Card Steam 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 24,
    nome: "Gift Card Steam 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 25,
    nome: "Gift Card Steam 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
];
