export const XboxCards = [
  {
    id: 1,
    nome: "Gift Card Xbox 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 2,
    nome: "Gift Card Xbox 250R$",
    valor: 270,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 3,
    nome: "Gift Card Xbox 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 4,
    nome: "Gift Card Xbox 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 5,
    nome: "Gift Card Xbox 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 5,
    nome: "Gift Card Xbox GamePass 3 Meses",
    valor: 90,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 5,
    nome: "Gift Card Xbox GamePass Ultimate 12 Meses",
    valor: 155,
    plataforma: "GiftCards",
    console: "Xbox",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
];
