export const Steam = [
  {
    id: 1,
    nome: "Gift Card Steam 100R$",
    valor: 110,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 2,
    nome: "Gift Card Steam 50R$",
    valor: 55,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 3,
    nome: "Gift Card Steam 150R$",
    valor: 160,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
  {
    id: 4,
    nome: "Gift Card Steam 200R$",
    valor: 220,
    plataforma: "GiftCards",
    console: "Steam pc",
    parcela: 5,
    descricao: "",
    quantidade: 1,
  },
];
